import type { FieldValue } from "./common";

type BALANCE_SHEET_FIELDS =
  | "assets"
  | "current_assets"
  | "cash_and_cash_equivalents"
  | "current_financial_assets"
  | "receivables"
  | "trade_receivables"
  | "trade_receivables_third_parties"
  | "trade_receivables_related_parties"
  | "other_receivables"
  | "other_receivables_third_parties"
  | "other_receivables_related_parties"
  | "inventories"
  | "prepaid_expenses"
  | "current_advances"
  | "prepaid_taxes"
  | "corporate_income_prepaid_taxes"
  | "other_prepaid_taxes"
  | "work_in_progress"
  | "contract_assets"
  | "other_current_assets"
  | "non_current_assets"
  | "non_current_receivables"
  | "non_current_receivables_from_related_parties"
  | "non_current_receivables_from_third_parties"
  | "investments"
  | "investment_in_associates"
  | "investment_in_joint_ventures"
  | "investments_using_equity"
  | "other_investments"
  | "fixed_assets"
  | "properties_assets"
  | "properties_assets_advances"
  | "properties_assets_rights"
  | "inventory_assets"
  | "others_assets"
  | "fixed_assets_depreciation"
  | "properties_depreciation"
  | "inventory_depreciation"
  | "others_depreciation"
  | "deferred_tax_assets"
  | "deferred_vat_input"
  | "goodwill"
  | "intangible_assets_ex_goodwill"
  | "other_non_current_non_financial_assets"
  | "deposits"
  | "claims_for_tax_refund"
  | "liabilities_and_equities"
  | "liabilities"
  | "current_liabilities"
  | "trade_payables"
  | "trade_payabless_third_parties"
  | "trade_payables_related_parties"
  | "other_payables"
  | "other_payabless_third_parties"
  | "other_payables_related_parties"
  | "other_current_financial_liabilities"
  | "other_current_non_financial_liabilities"
  | "short_term_loans"
  | "current_accrued_expenses"
  | "taxes_payables"
  | "corporate_income_taxes_payable"
  | "other_taxes_payables"
  | "current_maturities_of_non_current_liabilities"
  | "current_maturities_of_bank_loans"
  | "current_maturities_of_secured_loans"
  | "current_maturities_of_finance_lease_loans"
  | "current_maturities_of_other_borrowings"
  | "prepaid_income"
  | "advance_payment_liabilities"
  | "contract_liabilities"
  | "liabilities_union_savings"
  | "member_savings"
  | "member_special_savings"
  | "term_savings"
  | "voluntary_savings"
  | "non_current_liabilities"
  | "deferred_tax_liabilities"
  | "long_term_liabilities"
  | "employee_benefits_liabilities"
  | "long_term_bank_loans"
  | "long_term_finance_lease_loans"
  | "long_term_bonds_loans"
  | "long_term_other_borrowings"
  | "other_non_current_financial_liabilities"
  | "other_non_current_non_financial_liabilities"
  | "interest_bank_loan"
  | "deferred_vat_output"
  | "equities"
  | "equity_union_savings"
  | "special_savings"
  | "principal_savings"
  | "mandatory_savings"
  | "reserves"
  | "grant_funds"
  | "equities_attributable"
  | "common_stocks"
  | "additional_paid_in_capital"
  | "treasury_stocks"
  | "other_components_of_equity"
  | "retained_earnings"
  | "appropriated_retained_earnings"
  | "unappropriated_retained_earnings"
  | "dividen"
  | "non_controlling_interests"
  | "current_profit_loss"
  | "other_comprehensive_incomes";

type INCOME_STATEMENT_FIELDS =
  | "total_revenue"
  | "cost_of_sales_and_revenue"
  | "total_gross_profit_loss"
  | "operating_expenses"
  | "selling_expense"
  | "general_adm_expense"
  | "salary_and_benefit"
  | "transportation_expense"
  | "office_utilities"
  | "office_supplies"
  | "rental"
  | "depreciation_amortisation"
  | "operating_profit_loss"
  | "non_operating_income_expenses"
  | "non_operating_income"
  | "non_operating_expenses"
  | "finance_income"
  | "finance_cost"
  | "forex"
  | "income_other_comprehensive"
  | "non_controlling_interest"
  | "total_profit_before_tax"
  | "tax_income_expenses"
  | "total_profit_loss"
  | "total_comprehensive_income"
  | "earning_loss_per_share";

type BalanceSheetRead = Partial<
  Record<BALANCE_SHEET_FIELDS, FieldValue>
> & {
  [key: string]: FieldValue | undefined;
};

type IncomeStatementRead = Partial<
  Record<INCOME_STATEMENT_FIELDS, FieldValue>
> & {
  [key: string]: FieldValue | undefined;
};

export type FinancialStatement = {
  read?: BalanceSheetRead | IncomeStatementRead;
  status?: string;
  reason?: string;
  [key: string]: unknown;
};
